name: Deploy-Log-Event

on:
  push:
    branches:
      - main
    paths:
      - packages/lambda-log-event/**

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lambda-log-event
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.js --minify
          zip -j deploy.zip ./dist/index.js ./dist/geoip-country.dat ./dist/geoip-country6.dat
          aws lambda update-function-code --function-name=log-analytics-event --zip-file=fileb://deploy.zip
